version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: student_tracker_db # Set the default database to be created
    volumes:
      - ./mongodb-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d/ # Mount the init script for user creation
    networks:
      - app-network

  nextjs:
    build: .
    container_name: nextjs-app
    ports:
      - "4000:4000" # Map port 4000 on the host to port 3000 in the container
    environment:
      - PORT=4000 # Notice the correct format for the environment variable
      - MONGO_URI=mongodb://admin:root@mongodb-container:27017/student_tracker_db?authSource=admin
    depends_on:
      - mongodb
    networks:
      - app-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev -- -p 4000 # Ensure you're using development mode

volumes:
  mongodb-data:
    driver: local

networks:
  app-network:
    driver: bridge
